# Generated by Django 4.0.6 on 2022-07-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='55db3802d1ee40379a0ab7d9ba5b008f', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
