# Generated by Django 4.0.6 on 2022-07-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='e9294a121533478e934ec04328f655bf', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
